import streamlit as st
import requests
from PIL import Image
import io
import base64
import json
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure the page
st.set_page_config(
    page_title="Fundus Image Analysis",
    page_icon="👁️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
    <style>
    .main {
        background-color: #f5f5f5;
    }
    .stApp {
        max-width: 1200px;
        margin: 0 auto;
    }
    .prediction-box {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        margin: 10px 0;
    }
    .gradcam-container {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        margin: 10px 0;
    }
    .upload-box {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        margin: 10px 0;
        text-align: center;
    }
    .stButton>button {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
    .stButton>button:hover {
        background-color: #45a049;
    }
    </style>
    """, unsafe_allow_html=True)

# Title and description
st.title("👁️ Fundus Image Analysis")
st.markdown("""
    This application uses deep learning to analyze fundus images and detect various eye conditions.
    Upload a fundus image to get started.
""")

# Sidebar
with st.sidebar:
    st.header("About")
    st.markdown("""
        This tool uses an EfficientNet-B0 model trained on a large dataset of fundus images
        to detect various eye conditions including:
        
        - Diabetic Retinopathy (DR)
        - Glaucoma
        - Macular Degeneration
        - And many other conditions
        
        The model provides both a prediction and a Grad-CAM visualization to help understand
        the areas of the image that influenced the prediction.
    """)
    
    st.header("Instructions")
    st.markdown("""
        1. Upload a fundus image using the upload button
        2. Wait for the analysis to complete
        3. View the prediction and Grad-CAM visualization
        4. Download the results if needed
    """)

# File upload
uploaded_file = st.file_uploader("Choose a fundus image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Display the uploaded image
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_column_width=True)
    
    # Prepare the image for API request
    img_byte_arr = io.BytesIO()
    image.save(img_byte_arr, format='PNG')
    img_byte_arr = img_byte_arr.getvalue()
    
    # Create two columns for the results
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown('<div class="prediction-box">', unsafe_allow_html=True)
        st.subheader("Prediction")
        if st.button("Predict Disease"):
            try:
                files = {"file": ("image.png", img_byte_arr, "image/png")}
                response = requests.post("http://localhost:8000/api/v1/predict", files=files)
                if response.status_code == 200:
                    prediction = response.json()["prediction"]
                    st.success(f"Detected Condition: {prediction}")
                    st.info("""
                        **Disclaimer:** This prediction is generated by an AI model and is intended for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider with any questions you may have regarding a medical condition.
                    """)
                else:
                    st.error("Error getting prediction")
            except Exception as e:
                st.error(f"Error: {str(e)}")
        st.markdown('</div>', unsafe_allow_html=True)
    
    with col2:
        st.markdown('<div class="gradcam-container">', unsafe_allow_html=True)
        st.subheader("Attention Map")
        if st.button("Show Attention Map"):
            try:
                files = {"file": ("image.png", img_byte_arr, "image/png")}
                response = requests.post("http://localhost:8000/api/v1/predict-with-gradcam", files=files)
                if response.status_code == 200:
                    data = response.json()
                    gradcam_image = data["gradcam_image"]
                    st.image(gradcam_image, caption="Attention Map", use_column_width=True)
                    st.info("""
                        **About the Attention Map:**
                        The attention map (also known as Grad-CAM) highlights the regions of the fundus image that most influenced the AI model's prediction. Brighter or more colored areas indicate regions that were more important for the model's decision. This visualization can help provide insight into what the model is focusing on, but it should not be interpreted as a clinical explanation.
                    """)
                else:
                    st.error("Error getting attention map visualization")
            except Exception as e:
                st.error(f"Error: {str(e)}")
        st.markdown('</div>', unsafe_allow_html=True)
else:
    st.markdown('<div class="upload-box">', unsafe_allow_html=True)
    st.info("Please upload a fundus image to begin analysis")
    st.markdown('</div>', unsafe_allow_html=True) 